# Étape 1 : Build du projet
FROM maven:3.8.5-openjdk-11 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Étape 2 : Déploiement sur Tomcat
FROM tomcat:9.0-jdk11-corretto
RUN rm -rf /usr/local/tomcat/webapps/*
# Copie le war généré par l'étape 1
COPY --from=build /app/target/*.war /usr/local/tomcat/webapps/ROOT.war
EXPOSE 8080
CMD ["catalina.sh", "run"]