# Utiliser l'image officielle Nginx stable et légère
FROM nginx:alpine

# Supprimer les fichiers HTML par défaut de Nginx
RUN rm -rf /usr/share/nginx/html/*

# Copier le dossier 'dist' généré sur ton PC vers le dossier Nginx du conteneur
COPY dist /usr/share/nginx/html

# Exposer le port par défaut d'un serveur web
EXPOSE 80

# Lancer Nginx au premier plan
CMD ["nginx", "-g", "daemon off;"]